### ISSUE TITLE
Issue using code as per instruction.

### ISSUE THREAD

**Issue by prafiles** [anantzoid/Language-Modeling-GatedCNN#1]
Hey I tried running the code as per the instructions in README. All went well, except this error is thrown in trace.

`Traceback (most recent call last):
  File "main.py", line 68, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 42, in main
    summary_writer = tf.train.SummaryWriter(conf.summary_path, graph_def=sess.graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 110, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 82, in __init__
    graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/writer.py", line 309, in __init__
    super(FileWriter, self).__init__(event_writer, graph, graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/writer.py", line 91, in __init__
    graph_def=graph_def or maybe_graph_as_def))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 344, in create_meta_graph_def
    type(graph_def))
TypeError: ('graph_def must be of type GraphDef, not %s', <class 'tensorflow.python.framework.ops.Graph'>)
`

**Comment by prafiles** [comment]
Additional information. I'm on Tensorflow 0.12.1

**Comment by anantzoid** [comment]
It seems summary_writer got deprecated for 0.12.1. Please pull the latest commit to resolve the errors.
